### ISSUE TITLE
Cursor move to end when delete "." using a ui-number-mask

### ISSUE THREAD

**Issue by glumsoe** [assisrafael/angular-input-masks#122] opened 2015-09-21 12:23 UTC
See details here:
![mask - cursor move to end when delete](https://cloud.githubusercontent.com/assets/8768134/9991654/3dc5e0c2-606c-11e5-8e33-c512f63441db.png)
##

**Comment by assisrafael** [comment] 2017-09-23 15:51
Duplicate of #104

**Closed by assisrafael** 2017-09-23 15:51 UTC
Labels: enhancement
