### ISSUE TITLE
Enter number Amount with left handed style

### ISSUE THREAD

**Issue by dilip-borad** [assisrafael/angular-input-masks#144] opened 2015-12-04 12:37 UTC
Hello Guys,

I know number is is generally come with right side alignment. But actually i've some little bit problems during enter numbers with 2 decimals like
Example -
The default text style with mask is look like 0,00
Currently when i need to enter 12.00 i must need to enter amount 1200 but it will be possible that i'm just enter amount 12 and then rest of decimal .00 is automatically added at last and if user will need to change .00 values then he will change it itself by moving cursor.
But my requirement is to add 12 as a before .00 by default when i start entering amount.

Thanks in advance.
Dilip.

**Comment by dilip-borad** [comment] 2015-12-21 13:09
The another way to tell this is there is any possibility to trigger this input mask when onblur event is triggered.

**Comment by assisrafael** [comment] 2015-12-22 09:22
Related to #118 
Pull requests are welcome.

**Comment by assisrafael** [comment] 2016-10-11 09:15
Closing since it is a duplicate of #118.

**Closed by assisrafael** 2016-10-11 09:15 UTC
Labels: duplicate, enhancement
