### ISSUE TITLE
failing to initialize

### ISSUE THREAD

**Issue by eduardoarantes** [assisrafael/angular-input-masks#69] opened 2015-04-13 15:26 UTC
I'm trying to use the angular-input-masks but I'm getting the error below.

I already have a moment.js installed via another pluging angular-moment.

Uncaught Error: [$injector:modulerr] Failed to instantiate module clubeDoAdvogado due to:
Error: [$injector:modulerr] Failed to instantiate module oc.lazyLoad due to:
Error: [$injector:nomod] Module 'angular-momentjs' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Any idea on how to fix it?

Regards

**Comment by assisrafael** [comment] 2015-04-13 16:59
Which angular version you are using?

**Comment by eduardoarantes** [comment] 2015-04-13 17:45
Sorry.

 "bootstrap-3-datepicker": "~1.4.0",
    "font-awesome": "~4.3.0",
    "modernizr": "~2.8.3",
    "pnotify": "~2.0.1",
    "nanoscroller": "~0.8.5",
    "bootstrap": "~3.3.4",
    "jquery": "~2.1.3",
    "moment": "~2.9.0",
    "angular": "~1.3.15",
    "angular-resource": "~1.3.15",
    "angular-ui-router": "~0.2.13",
    "angular-mocks": "~1.3.15",
    "chartjs": "~1.0.2",
    "flot": "~0.8.3",
    "oclazyload": "~0.6.3",
    "angular-local-storage": "~0.1.5",
    "angular-loading-bar": "~0.7.1",
    "angular-animate": "~1.3.15",
    "select2": "~3.5.2",
    "angular-bootstrap": "~0.12.1",
    "bower": "*",
    "install": "~1.0.4",
    "animate.css": "~3.2.6",
    "angucomplete-alt": "~0.0.38",
    "angular-sanitize": "~1.3.15",
    "sparkline": "~2.1.2",
    "angular-bootstrap-calendar": "~0.8.1",
    "angular-locale": "~0.1.9",
    "angular-moment": "~0.9.2",
    "angulartics": "~0.17.2",
    "angular-locale-pt-br": "~1.3.15",
    "angular-input-masks": "~1.4.2"

**Comment by assisrafael** [comment] 2015-04-13 17:51
This lib is only tested with angular 1.2.X.
In the next weeks I'm planning to add 1.3 support.
Meanwhile, can you include a global version of moment.js into your app and check if the error persist?

**Comment by eduardoarantes** [comment] 2015-04-13 17:53
how do I do this?

**Comment by assisrafael** [comment] 2015-04-14 21:22
just include de script (moment.js) in your html.

**Comment by eduardoarantes** [comment] 2015-04-14 21:45
It's already there

**Comment by assisrafael** [comment] 2015-04-14 22:52
So it seems that the problem is with angular 1.3.

**Comment by assisrafael** [comment] 2015-06-07 21:26
Landed in v1.5.1.
Check the standalone build.

**Closed by assisrafael** 2015-06-07 21:26 UTC
Labels: bug
