### ISSUE TITLE
Problema com instalação via Bower com Angular v1.3.15 

### ISSUE THREAD

**Issue by rafael-augusto** [assisrafael/angular-input-masks#140] opened 2015-11-27 19:32 UTC
1>  bower angular-input-masks#2.1.0 cached git://github.com/assisrafael/bower-angular-input-masks.git#2.1.0
1>  bower angular-input-masks#2.1.0         validate 2.1.0 against git://github.com/assisrafael/bower-angular-input-masks.git#2.1.0
1>  bower string-mask#~0.2.0                  cached git://github.com/the-darc/string-mask.git#0.2.2
1>  bower string-mask#~0.2.0                validate 0.2.2 against git://github.com/the-darc/string-mask.git#~0.2.0
1>  bower angular#~1.3.16                     cached git://github.com/angular/bower-angular.git#1.3.20
1>  bower angular#~1.3.16                   validate 1.3.20 against git://github.com/angular/bower-angular.git#~1.3.16
1>  bower br-validations#~0.2.4               cached git://github.com/the-darc/br-validations.git#0.2.4
1>  bower br-validations#~0.2.4             validate 0.2.4 against git://github.com/the-darc/br-validations.git#~0.2.4
1>  bower angular#>= 1.0.2                    cached git://github.com/angular/bower-angular.git#1.4.8
1>  bower                                  ECONFLICT Unable to find suitable version for angular

Ao realizar o download da biblioteca do angular-input-masks manualmente, notei que no packages.json ele está utilizando:   

"devDependencies": {
    "angular": "~1.3.16",
...
}

**Comment by assisrafael** [comment] 2015-12-02 11:58
This seems to be a problem with the pinned versions in your bower.json.

**Comment by assisrafael** [comment] 2015-12-02 12:00
Duplicate of #139

**Closed by assisrafael** 2015-12-02 12:00 UTC
Labels: question
