### ISSUE TITLE
Reverse input-mode

### ISSUE THREAD

**Issue by GVersluiss** [assisrafael/angular-input-masks#154] opened 2016-01-10 12:46 UTC
Is it possible to switch the input-mode from left-to-right instead of right-to-left.

In example: when using "ui-money-mask" and I type "50" it shows "$0.50".
I think it would make much more sense when it shows "$50.00".

**Comment by assisrafael** [comment] 2016-01-14 15:38
No, we do not have this feature.

**Comment by skarface** [comment] 2016-02-18 09:18
+1 Welcome feature to implement.

**Comment by vincentfierant** [comment] 2016-05-31 09:04
+1 This would be great.

**Comment by marcomafessolli** [comment] 2016-06-21 10:33
Related with #144 and #118

**Comment by avlima** [comment] 2016-09-09 17:55
+ 1

**Comment by assisrafael** [comment] 2016-10-11 09:14
Duplicate of #118 (thank you @marcomafessolli)

**Closed by assisrafael** 2016-10-11 09:14 UTC
Labels: question
