### ISSUE TITLE
The focus pointer move up to value's end when mask applies dot (thousand, million, billion)

### ISSUE THREAD

**Issue by thelimarenan** [assisrafael/angular-input-masks#237] opened 2016-11-24 17:07 UTC
If user wants edit a money value, but pointer focus to be in middle of input element, at the moment the mask to applies the point, be it to separate thousand, million, billion, or whatever comes forward, the cursor focuses at end of input element.

For example, look at this situation:

* the input contains the value $ 543.00;
* the user selects the input cursor to be between 5 and 4 (something like - 5|43,00);
* When entering the next character (for example "9"), the mask will put the point of thousands;
* Then, the focus changes to the end of the input (something like - 5.943,00|);
* When entering the next character (for example "8"), the value will be affected as follows: 59.430,08 |

What could be causing this?
Or should I view it as a universal convention for entering monetary values?

**Comment by gabrielfreire** [comment] 2016-11-28 14:36
I am having the same issue

**Comment by jayrmotta** [comment] 2016-12-21 18:22
It's related to the issues https://github.com/assisrafael/angular-input-masks/issues/242 and https://github.com/assisrafael/angular-input-masks/issues/228

And it's potentially solved by the pull request https://github.com/assisrafael/angular-input-masks/pull/211

**Comment by assisrafael** [comment] 2017-09-23 15:43
Duplicate of #104

**Closed by assisrafael** 2017-09-23 15:43 UTC
