### ISSUE TITLE
Mask not working on Samsung devices [Ionic]

### ISSUE THREAD

**Issue by clluiz** [assisrafael/angular-input-masks#104] opened 2015-07-28 20:57 UTC
I'm using this great directive in my app developed using ionic framework. But when I use the cpf mask, it doesnt work well,but this happens only on Samsung devices. Someone can help-me?
##

**Comment by assisrafael** [comment] 2015-07-29 06:30
Can you describe more the scenario (angular and ionic versions)?

**Comment by sergiolopes** [comment] 2015-09-05 17:40
Same here. Ionic 1.0.1, which bundles Angular 1.3.13.

When typing on a mask thr cursos goes crazy and is placed in the middle of the field. Number get all mixed up

**Comment by diegogurgel** [comment] 2015-11-10 02:17
Same here on Samsung galaxy S3

**Comment by matheusd** [comment] 2015-11-13 19:45
I went down the rabbit role with this one. I'm documenting my search process for posterity.

Brief rundown of the problem: After typing the third fourth digit on a CPF-masked field, the "." is added to the left of the fourth digit but the keyboard caret does not move to the end of the text field, causing the following typed digits to appear out of order.

I tested on my phone (4.2 android) and the mask did not work. I tested on another phone (android 4.4) and it worked. Tested on a 4.2 android, but through chrome and the bug did not happen.

What changed between 4.2 and 4.4? The Webview component was updated! So, let's try on the emulator: same situation (works on Webviews on API 19+, but not older than that).

So, now I'm certain the problem is the webview component. But how to debug and find out the specific error? After many attempts at debugging, I give up and try to find a comparable browser to run on my desktop and check if the error also happens.

After some more digging, I find the repository for old chromium builds [1], pick up an older version and test: the problem happens.

Now I'm on a roll, and I **really*** want to figure out what caused the problem, since it's clearly a browser issue. I start bisecting through old chromium versions until I find a matching pair of versions that don't/do work. Specifically versions 206116 [2] (mask doesn't work) and 206150 [3] (mask works).

Checking their version changes, on version 206150 webkit was updated, and among the changelog there is a reference to a suspicious looking error (webkit's 110742) [4], which describes a problem of receiving incorrect values for selection start/end on input events. So, this is probably the root cause of the problem: angular's formatter is updating the input but on older webkit browsers (such as the one that runs inside webviews on android < 4.4) the events and input updating are not properly handled.

After a few tests, I came up with an ugly hack to fix the problem. On file mask-factory.js, on the link function for the directive, add the following:

element.on('input', function () {
    var that = this;
    setTimeout(function () {
        that.setSelectionRange(that.value.length, that.value.length)
    }, 100);
});

Suggestions for a cleaner solution?

[1] https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html

[2] https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/206116/

[3] https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/206150/

[4] https://bugs.webkit.org/show_bug.cgi?id=110742

**Comment by GustavoCostaW** [comment] 2015-12-01 23:41
using ui-number-mask="2"

When typing on a mask the cursor goes crazy and is placed in the middle of the field. Numbers get all mixed up

In Samsung devices 4.4 <

+1

**Comment by vincequeiroz** [comment] 2016-02-02 17:33
The problem it's cause by [predictive text of the Samsung](http://www.samsung.com/us/support/answer/ANS00030027/237240/). I changed the keyboard for Google and it worked.
If input type is number predictive text is disabled, but angular-input-masks not work, because angular check value is number.
I tried disable predictive text with autocomplete, autocapitalize, and autocorrect, but too not work.
I tried set number pattern in input, but numeric keyboard not is showing.

Someone found a solution?

**Comment by luco** [comment] 2016-05-04 12:06
+1 Here

**Comment by luco** [comment] 2016-06-13 13:26
@matheusd Where did you put this? I couldn't find it.

**Comment by matheusd** [comment] 2016-06-13 14:02
@luc: I haven't really messed around with this since my first answer, but I believe it was somewhere around here:

https://github.com/assisrafael/angular-input-masks/blob/master/src/node_modules/mask-factory.js#L17

**Comment by mardonedias** [comment] 2016-07-07 19:29
**ui-number-mask** does not work **Browser Android 4.2.1** , the input type is "tel " when the field receives focus, not active masks . When the cursor gets digit at the left and going adding the values ​​before the mask.

**Comment by neomacedo** [comment] 2016-08-12 14:06
w8ng for updates

**Comment by MrRobWad** [comment] 2016-08-25 17:45
+1. Using a custom directive to render a simple text input (not this plugin). When selecting a predictive text option on Samsung keyboard, the directive gets an empty value for the model. Adding the HTML5 attributes to disable predictive text do not prevent this issue. Only solution so far has been to disable predictive text or use a different keyboard, though those are client side solutions. Trying to determine a proper solution.

**Comment by lopesricardo** [comment] 2016-10-11 12:18
This trouble is caused by autocomplete function of SmartKeyboad.

**Comment by ccaiolopes** [comment] 2016-10-11 15:05
And how to disable it?

**Comment by ccaiolopes** [comment] 2016-10-11 15:11
I put this and solved my problem

<input autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" />

**Comment by lopesricardo** [comment] 2016-10-14 11:47
You have to access keyboard options, Samsung Keyboard, and disable Smart Text.

**Comment by fredfmm** [comment] 2017-01-03 13:06
I still with the same problem. 
Only for samsung keyboard. 
I tried all suggestions but not worked!
Anyone can help! please.

**Comment by wcustodio** [comment] 2017-02-07 20:47
The problem still exists. Any solution?

**Comment by fredfmm** [comment] 2017-02-13 23:43
I found one way!
You can add  mask.js from the ui-mask repository.
They fixed this bug adjusting the cursor when you tap.
This is not the best solution, but works.

**Comment by ealbuquerque** [comment] 2017-03-07 20:07
@fredfmm Could you put your workarround here?

**Comment by ealbuquerque** [comment] 2017-03-09 13:47
Any solution?

**Comment by cesarvargas00** [comment] 2017-03-21 13:10
@assisrafael any solution?

**Comment by fjcunha** [comment] 2017-04-03 15:44
I found a workaround.
Consists of always sending the cursor to the end of the value in the "onchange" event of the input.
In Ionic 2 "onchange" event is (input)="someFunction($event)", so go to the code:

i'm using this mask:
`public cpfmask = [/[0-9]/,/[0-9]/,/[0-9]/,'.',/[0-9]/,/[0-9]/,/[0-9]/,'.',/[0-9]/,/[0-9]/,/[0-9]/,'-',/[0-9]/,/[0-9]/];`

on input in **html file**:
`<ion-input type="text" (input)='onChangeMaskInput($event)' [textMask]="{mask: cpfmask}"[(ngModel)]="modelVariable"></ion-input>`

now the onChangeMaskInput($event) method implementation on **TS file**:

```
onChangeMaskInput(ev){
    setTimeout(() => {
      ev.target.selectionStart = ev.target.value.length;
      ev.target.selectionEnd = ev.target.value.length;
    },10);
}
```

**Comment by Connor-Knabe** [comment] 2017-04-06 13:13
@matheusd this seemed to fix the issue thank you!

**Comment by ealbuquerque** [comment] 2017-04-06 13:46
@fjcunha thanks!

**Angular 1 Directive**
`
.directive('input', input);
function input() {
	return {
	  restrict: 'E',
	  link: function ($scope, $element, $attrs) {
	    $element.bind('keydown', function ($event) {
	      $event.target.selectionStart = $event.target.value.length;
	      $event.target.selectionEnd = $event.target.value.length;
	    });
	  }
	}
}
`

**Comment by camilaazuma** [comment] 2017-04-19 19:47
@ealbuquerque solution works. But has a side effect. This directive applies the behavior to all fields of the application.
In my case, I just wanted this to my CPF field, so I check whether the CPF mask is being applied before binding to the event.
And when editing the field, if the cursor is in the middle of the text, it jumps to the end too, so I'm also checking the keyCode of event, and preventing the behavior when backspace is pressed.

```javascript
.directive('input', input);
function input($timeout) {
    return {
        restrict: 'E',
        link: function ($scope, $element, $attrs) {
            if($attrs.$attr.uiBrCpfMask){
                $element.bind('keydown', function ($event) {
                    if($event.keyCode != 8){
                        $timeout(function () {
                            $event.target.selectionStart = $event.target.value.length;
                            $event.target.selectionEnd = $event.target.value.length;
                        });
                    }
                });
            }
        }
    };
}
```

**Comment by ealbuquerque** [comment] 2017-04-20 12:17
@camilaazuma Its solution was very good, but in the case of a workaround, I believe that an exclusive directive for these input fields would be even more performative.

The fact was that my application did not suffer any kind of slowness... which made me not spend even more time with a very sophisticated implementation.

ZECA.

**Comment by strikegamer** [comment] 2017-04-24 20:54
@ealbuquerque your solution works fine here. Thanks!

**Comment by rafaellopes96** [comment] 2017-07-05 17:30
I made a another solution, that fix the problem about tiping something in the middle of the input:

`link: function ($scope, $element, $attrs) {
                // filter the element using attributes
                if ($attrs.type != "text") {
                    $element.bind('keydown', function ($event) {
                        if($event.keyCode != 8){
                            $timeout(function () {
                                var position = $element[0].selectionStart;
                                if(position ==  4 || position ==  8 || position ==  12){
                                    $event.target.selectionStart = position + 1;
                                    $event.target.selectionEnd = position + 1;
                                }
                            });
                        }
                    });
                }
            }`

**Comment by renanss** [comment] 2017-08-09 20:02
@ealbuquerque that worked for me thanks.
I just need to add a restrict:

> restrict: 'EA',

**Comment by assisrafael** [comment] 2017-09-23 15:53
Duplicate of #115

**Closed by assisrafael** 2017-09-23 15:53 UTC
Labels: question

**Comment by evertonz23** [comment] 2017-09-23 17:06
What's the solution?

**Comment by lucasjorge944** [comment] 2017-09-25 17:50
Its works.. from @ealbuquerque 
`.directive('input', input);
function input($timeout) {
  return {
    restrict: 'E',
    link: function ($scope, $element, $attrs) {
      if($attrs.$attr.uiBrCpfMask){
        $element.bind('keydown', function ($event) {
          if($event.keyCode != 8){
            $timeout(function () {
              $event.target.selectionStart = $event.target.value.length;
              $event.target.selectionEnd = $event.target.value.length;
            });
          }
        });
      }
    }
  };
}`

If you want, create a directive with a different name, and call the directive in the input, here is my example:
`module.exports = function(ngModule){
    ngModule.directive('maskFix', function($timeout) {
        return {
            require: 'ngModel',
            link: function($scope, $element, $attrs) {
              $element.bind('keydown', function ($event) {
                $timeout(function () {
                  $event.target.selectionStart = $event.target.value.length;
                  $event.target.selectionEnd = $event.target.value.length;
                });
              });            
            }
        };
    });
};`

`<input type="tel" mask-fix name="phone" ng-model="vm.customer.phone" ui-br-phone-number required>`

**Comment by lennonjesus** [comment] 2018-02-02 20:07
Changing the input type **from** `text` **to** `tel` worked perfectly for me. 👍
