### ISSUE TITLE
separate decimals when writing the comma symbol

### ISSUE THREAD

**Issue by fernandooj** [assisrafael/angular-input-masks#219] opened 2016-09-23 22:00 UTC
Hello, I'm using your library and it has worked well, but I have this requirement and let me know if I can help,
if i digit number integer  shows me the intener ej: digit 95 showme 95 
but if I need one decimal digit , and then the number, ej: digit ,95 and show me 0.95

regards
##

**Comment by assisrafael** [comment] 2017-09-23 15:46
Duplicate of #165

**Closed by assisrafael** 2017-09-23 15:46 UTC
