### ISSUE TITLE
ui-number-mask without rounding

### ISSUE THREAD

**Issue by leandrolimasi** [assisrafael/angular-input-masks#179] opened 2016-04-22 16:56 UTC
When I use the ui-number-mask , rounding occurs after a certain number of decimal places.

Ex: 9,999,999,999,999,999 rounds 10000000000000000 in ng-model . How can I make the plugin not round the values ​​in any way ?

**Comment by kanodoe** [comment] 2016-04-27 13:33
Agree +1

**Comment by assisrafael** [comment] 2016-04-27 14:29
Duplicate of #158

**Closed by assisrafael** 2016-04-27 14:29 UTC
