### ISSUE TITLE
Methods Save

### ISSUE THREAD

**Issue by lclpedro** [assisrafael/angular-input-masks#288] opened 2017-07-17 20:03 UTC
Hello, is possible save point? CPF, CPNJ, Dates?

**Comment by assisrafael** [comment] 2017-09-23 14:21
I'm not sure what is your question about. Can you explain it with an example?

**Comment by lclpedro** [comment] 2017-09-24 19:10
Is saved in database 0123467890! Is possible save 012.345.678-90? Save points..

**Comment by assisrafael** [comment] 2017-09-25 02:29
Not without extra code.
Take a look at https://github.com/assisrafael/angular-input-masks#filters
Duplicate of #172

**Closed by assisrafael** 2017-09-25 02:29 UTC
Labels: question
