### ISSUE TITLE
Start typing from the left by default (ui-money-mask)

### ISSUE THREAD

**Issue by emerinohdz** [assisrafael/angular-input-masks#274] opened 2017-05-09 17:00 UTC
When typing a number using ui-money-mask, when you give the input focus and start typing it always start from the right, which causes leading zeros to always be typed (e.g. if I want to type number 22, I always have to type 22 plus the two leading zeros 00, so that the final number ends up being 22.00).

Is there a way to change this behavior?

**Comment by Devqon** [comment] 2017-08-17 11:25
Have you found a way around for this?

**Comment by assisrafael** [comment] 2017-09-23 15:45
Duplicate of #219

**Closed by assisrafael** 2017-09-23 15:45 UTC
