### ISSUE TITLE
Masked value submitted

### ISSUE THREAD

**Issue by polapolo** [assisrafael/angular-input-masks#222] opened 2016-10-03 09:11 UTC
Hi, i got a problem with ui-number-mask when submitting the form that i masked.
I want to submit the raw data (not masked one), but the masked one is submitted.
Any ideas? Thank you
angular-input-masks version : v2.4.0
##

**Comment by assisrafael** [comment] 2017-09-23 14:59
Duplicate of #221

**Closed by assisrafael** 2017-09-23 14:59 UTC
