### ISSUE TITLE
Cursor position is lost when deleting characters.

### ISSUE THREAD

**Issue by vivekkumar27june88** [assisrafael/angular-input-masks#229] opened 2016-10-30 17:37 UTC
Hi,

Suppose I have entered the phone number and then I tried to delete the `(` character, then this character is deleted and cursor is put at the end.

It will be more usable, if  user tries to delete  formatting character, then instead of deleting it should place the character before the formatting character.

Thanks

**Comment by vivekkumar27june88** [comment] 2016-10-31 11:40
Replying to my own question may be helpful to other if getting the same problem

Need to implement directive which can also set cursor as in code below

```

ngModelController.$parsers.unshift(function (viewValue) {
				var plainNumber = viewValue.replace(/ /g, '');
				// $log.info(`viewValue = ${viewValue}`);
				console.log(`$modelValue = ${ngModelController.$modelValue} | $viewValue = ${ngModelController.$viewValue} | viewValue = ${viewValue} | cursorPos = ${cursor.getCursorPos(elem[0])} | oldVal = ${oldVal}`);
				var newVal = ""
				for (var i = 0; i < plainNumber.length; i++) {
					if (i === 3 || i === 6) {
						newVal += " ";
					}
					newVal += plainNumber[i];
				}

				if(newVal === viewValue) {
					return viewValue;
				}

				// $log.info(`newVal = ${newVal}`);
				var lastCursorPos = cursor.getCursorPos(elem[0]);
				elem.val(newVal);
				ngModelController.$setViewValue(newVal);
				ngModelController.$render();

				//cursor.setCursorPos(cursor.getCursorPos(elem[0]) + 1, elem[0]);
				elem[0].setSelectionRange(lastCursorPos + 1, lastCursorPos + 1);
				oldVal = newVal;

				return plainNumber;
			});
```

**Comment by assisrafael** [comment] 2017-09-23 15:43
Duplicate of #104

**Closed by assisrafael** 2017-09-23 15:43 UTC
